blank_issues_enabled: false
contact_links:
  - name: Security report
    url: https://github.com/intelli-cave/human-activity-recognition-datasets/security/policy
    about: Please follow the security policy for reporting vulnerabilities.
