blank_issues_enabled: false
contact_links:
  - name: Security report
    url: https://github.com/your-org/human-activity-intelligence-atlas/security/policy
    about: Please follow the security policy for reporting vulnerabilities.
